Backend/Core/Lab/HumanResourcesApp_16_12_2024_Identity/HumanResourcesApp/HumanResourcesApp/Areas/Accounting/Controllers/AccountingPayrollController.cs
using Microsoft.AspNetCore.Mvc;
using HumanResourcesApp.Data;
using HumanResourcesApp.Areas.Accounting.Models;

namespace HumanResourcesApp.Areas.Accounting.Controllers
{
    [Area("Accounting")]  // Same as Model name in Area
    public class AccountingPayrollController : Controller
    {
        #region Fields
        private AppDbContext _dbContext;
        #endregion

        #region Constructors
        public AccountingPayrollController(AppDbContext dbContext)
        {
            this._dbContext = dbContext;
        }
        #endregion
        [HttpGet]
        public IActionResult Index()
        {
            var AccountingPayroll = _dbContext.AccountingPayrolls.ToList();
            return View(AccountingPayroll);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(AccountingPayroll accountingPayroll)
        {
          
          
            accountingPayroll.TS = DateTime.Now;

            _dbContext.Add(accountingPayroll);
            _dbContext.SaveChanges();
           
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = _dbContext.AccountingPayrolls.FirstOrDefault(acc => acc.Id == id);
          
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(int id, AccountingPayroll accountingPayroll)
        {
            var model = _dbContext.AccountingPayrolls.FirstOrDefault(acc => acc.Id == id);

            if (model != null)
            {
                model.PayrollAmount = accountingPayroll.PayrollAmount;
                model.TS = DateTime.Now;

                _dbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(accountingPayroll);
        }
    }
}

Backend/Core/Lab/HumanResourcesApp_16_12_2024_Identity/HumanResourcesApp/HumanResourcesApp/Controllers/EmployeeController.cs
using HumanResourcesApp.Data;
using HumanResourcesApp.Models;
using HumanResourcesApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace HumanResourcesApp.Controllers
{
    public class EmployeeController : Controller
    {
        private AppDbContext _dbContext;

        public EmployeeController(AppDbContext appDbContext)
        {
            this._dbContext = appDbContext;
        }

        // Show all Employees in the Employees table
        public IActionResult Index()
        {
            // Relation between Employees and Departments
            //var employees = (
            //    from emp in _dbContext.Employees
            //    join dep in _dbContext.Departments
            //    on emp.DepartmentId equals dep.Id

            //    select new Employee
            //    {
            //        Id = emp.Id,
            //        EmployeeName = emp.EmployeeName,
            //        EmployeeEmail = emp.EmployeeEmail,
            //        HiringDate = emp.HiringDate,
            //        DepartmentId = emp.DepartmentId,
            //        Department = dep
            //    }
            //    ).ToList();


            var employees = _dbContext.Employees.Include(emp => emp.Department);  // map Employees props with Department.



            return View(employees);
        }

        // Create or add a new employee - Call the Create View
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.DepartmentList = _dbContext.Departments.ToList();
            return View();
        }
        // Add the created employee above from Create - [HttpGet] to the Employees table
        [HttpPost]
        public IActionResult Create(Employee employee)
        {
            if (employee != null)
            {
                _dbContext.Employees.Add(employee);
                _dbContext.SaveChanges();

                return RedirectToAction("index");
            }
            else
            {
                return View();
            }
        }

        // Call the Edit Employee View
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.DepartmentList = _dbContext.Departments.ToList();

            var model = _dbContext.Employees.Where(emp => emp.Id == id).FirstOrDefault();

            return View(model);
        }
        // Update edited employee information from Edit- HttpGet and save them in the DB.
        [HttpPost]
        public IActionResult Edit(int id, Employee employee)
        {
            var emp = _dbContext.Employees.Where(emp => emp.Id == id).FirstOrDefault();

            emp.EmployeeName = employee.EmployeeName;
            emp.DepartmentId = employee.DepartmentId;
            emp.EmployeeEmail = employee.EmployeeEmail;
            emp.Department = employee.Department;
            emp.HiringDate = employee.HiringDate;
            emp.BasicSalary = employee.BasicSalary;

            _dbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        // Remove selected employee from Employee table in the DB
        [HttpGet]
        public IActionResult Delete(int id, Employee employee)
        {
            var model = _dbContext.Employees.Where(emp => emp.Id == id).FirstOrDefault();
            if (model != null)
            {
                _dbContext.Employees.Remove(model);
                _dbContext.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult EmployeesReport()
        {
            var employees = _dbContext.Employees.ToList();
            var payrolls = _dbContext.Payrolls.ToList();

            var model = new EmployeeReportViewModel
            {
                EmployeeCount = employees.Count(),
                TotalBasicSalries = employees.Sum(emp => emp.BasicSalary),
                TotalSSA = payrolls.Sum(emp => emp.SocialSecurityAmount),
                TotalBonuses = payrolls.Sum(emp => emp.Bonus),
                TotalNetSalaries = payrolls.Sum(emp => emp.NetSalary)
            };

            return View(model);
        }
    }
}

Backend/Core/Lab/HumanResourcesApp_16_12_2024_Identity/HumanResourcesApp/HumanResourcesApp/Controllers/PayrollController.cs
using HumanResourcesApp.Data;
using HumanResourcesApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;  // for using ViewBag
using Microsoft.EntityFrameworkCore;

namespace HumanResourcesApp.Controllers
{
    public class PayrollController : Controller
    {
        #region Fields
        private AppDbContext _dbContext;
        #endregion

        #region Constructors
        public PayrollController(AppDbContext appDbContext)
        {
            this._dbContext = appDbContext;
        }
        #endregion

        #region Action Methods

        #endregion
        public IActionResult Index()
        {
            var payroll = _dbContext.Payrolls.Include(pay => pay.Employee);
            return View(payroll);
        }

        [HttpGet]
        public IActionResult Create()
        {
            // Employee object drop-menu in Create View
            ViewBag.EmployeesList = new SelectList
                (
                    _dbContext.Employees.ToList(),
                    "Id", "EmployeeName"
                );

            return View();
        }
        [HttpPost]
        public IActionResult Create(Payroll payroll)
        {
            payroll.CreatedBy = "Admin";
            payroll.TS = DateTime.Now;
            CalculateNetSalary(payroll);

            _dbContext.Payrolls.Add(payroll);
            _dbContext.SaveChanges();

            return RedirectToAction("Index");
        }
        public void CalculateNetSalary(Payroll payroll)
        {
            var employee = _dbContext.Employees.FirstOrDefault(emp => emp.Id == payroll.EmployeeID);

            if (employee != null)
            {
                payroll.BasicSalary = employee.BasicSalary;

                var leaves = Convert.ToDecimal(payroll.Leaves) * (employee.BasicSalary / 30 / 8);
                payroll.NetSalary = employee.BasicSalary + payroll.Bonus - payroll.SocialSecurityAmount - leaves;
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.EmployeesList = new SelectList
                (
                    _dbContext.Employees.ToList(),
                    "Id", "EmployeeName"
                );
            var model = _dbContext.Payrolls.Where(pay => pay.Id == id).FirstOrDefault();

            return View("Create", model);
        }
        [HttpPost]
        public IActionResult Edit(int id, Payroll payroll)
        {
            var model = _dbContext.Payrolls.Where(payroll => payroll.Id == id).FirstOrDefault();

            model.EmployeeID = payroll.EmployeeID;
            model.PayrollDate = payroll.PayrollDate;
            model.Bonus = payroll.Bonus;
            model.SocialSecurityAmount = payroll.SocialSecurityAmount;
            model.Leaves = payroll.Leaves;
            model.NetSalary = payroll.NetSalary;
            model.Employee = payroll.Employee;

            _dbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Delete(int id, Payroll payroll)
        {
            var model = _dbContext.Payrolls.Where(emp => emp.Id == id).FirstOrDefault();
            if (model != null)
            {
                _dbContext.Payrolls.Remove(model);
                _dbContext.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

        // BasicSalary - Jquery: Ajax function url
        [HttpGet]
        public ActionResult<decimal> GetBasicSalary(int employeeId)
        {
            var basicSalary = _dbContext.Employees.FirstOrDefault(emp => emp.Id == employeeId).BasicSalary;

            return basicSalary;
        }
    }
}

Backend/Core/Lab/HumanResourcesApp_16_12_2024_Identity/HumanResourcesApp/HumanResourcesApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HumanResourcesApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HumanResourcesApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HumanResourcesApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Payroll" asp-action="Index">Payroll</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="EmployeesReport">Reports</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Accounting" asp-controller="AccountingPayroll" asp-action="Index">Accounts</a>
                        </li>
                    </ul>
                    
                    <div>
                        @{
                            <!---In case a user was signed already-->
                            if (_signInManager.IsSignedIn(User))
                            {
                                <p>
                                    Welcome @User.Identity?.Name |
                                    <a
                                       asp-action="Logout" 
                                       asp-controller="Account">
                                        SignOut
                                    </a>
                                    <a 
                                       asp-action="Manage"
                                       asp-controller="Account">
                                        Manage
                                    </a>
                                </p>

                            }
                            else
                            {
                                <p>
                                    <a asp-action="Login" asp-controller="Account">
                                        SignIn
                                    </a>
                                </p>
                            }
                        }
                    </div>    
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HumanResourcesApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>