Backend/Core/Practice/HumanResourcesApp/HumanResourcesApp/Areas/Accounting/Controllers/AccPayrollController.cs
// Ignore Spelling: acc
// Ignore Spelling: App

using HumanResourcesApp.Areas.Accounting.Models;
using HumanResourcesApp.Data;
using Microsoft.AspNetCore.Mvc;

namespace HumanResourcesApp.Areas.Accounting.Controllers
{
    [Area("Accounting")]
    public class AccPayrollController : Controller
    {
        #region Fields
        private AppDbContext _dbContex;
        #endregion

        #region Constructors
        public AccPayrollController(AppDbContext appDbContext)
        {
            this._dbContex = appDbContext;
        }
        #endregion

        #region Action Methods

        public IActionResult Index()
        {
            var model = _dbContex.AccPayrolls.ToList();
            return View(model);
        }
        #region Create

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(AccPayroll accPayroll)
        {
            accPayroll.TS = DateTime.Now;
            _dbContex.AccPayrolls.Add(accPayroll);
            _dbContex.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        #endregion

        #region Edit
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = _dbContex.AccPayrolls
                .FirstOrDefault(acc => acc.Id == id);

            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(int id, AccPayroll accPayroll)
        {
            var model = _dbContex.AccPayrolls
                .FirstOrDefault(acc => acc.Id == id);

            if (model != null)
            {
                model.PayrollAmount = accPayroll.PayrollAmount;
                model.TS = accPayroll.TS;
                _dbContex.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            return View(accPayroll);
        }
        #endregion

        #region Delete
        public ActionResult Delete()
        {
            var model = _dbContex.AccPayrolls.FirstOrDefault();
            _dbContex.AccPayrolls.Remove(model);
            _dbContex.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        #endregion

        #endregion
    }
}

Backend/Core/Practice/HumanResourcesApp/HumanResourcesApp/Controllers/DepartmentController.cs
using HumanResourcesApp.Data;
using HumanResourcesApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace HumanResourcesApp.Controllers
{
    public class DepartmentController : Controller
    {
        private AppDbContext _dbContext;

        // Passing DbContext to the Controller here
        public DepartmentController(AppDbContext appDbContext)
        {
            this._dbContext = appDbContext;
        }

        // Show all departments in the Departments table
        [HttpGet]
        public IActionResult Index()
        {
            var departments = _dbContext.Departments
                .OrderBy(dep => dep.DepartmentName)      // Sort alphabetically A-Z
                .ToList();
            return View(departments);
        }

        // Create or add a new department - Call the Create View
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        // Add the created new department above from Create - [HttpGet] to the Departments table
        [HttpPost]
        public IActionResult Create(Department department)
        {
            _dbContext.Departments.Add(department);
            _dbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = _dbContext.Departments.Where(dept => dept.Id == id).FirstOrDefault();

            return View("Create", model);  // View(ViewName, Object)
        }
        [HttpPost]
        public IActionResult Edit(int id, Department department)
        {
            var model = _dbContext.Departments.Where(dept => dept.Id == id).FirstOrDefault();

            model.DepartmentName = department.DepartmentName;
            _dbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        // Remove a Department
        [HttpGet]
        public IActionResult Delete(int id, Department department)
        {
            var model = _dbContext.Departments.Where(dept => dept.Id == id).FirstOrDefault();

            if (model != null)
            {
                _dbContext.Departments.Remove(model);
                _dbContext.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Backend/Core/Practice/HumanResourcesApp/HumanResourcesApp/Controllers/EmployeeController.cs
using HumanResourcesApp.Data;
using HumanResourcesApp.Models;
using HumanResourcesApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace HumanResourcesApp.Controllers
{
    public class EmployeeController : Controller
    {
        private AppDbContext _dbContext;

        public EmployeeController(AppDbContext appDbContext)
        {
            this._dbContext = appDbContext;
        }

        // Show all Employees in the Employees table
        public IActionResult Index()
        {
            var employees = _dbContext.Employees.Include(emp => emp.Department);  // map/join Employees props with Department.

            return View(employees);
        }

        // Create or add a new employee - Call the Create View
        [HttpGet]
        public IActionResult Create()
        {
            // Department drop-down menu
            ViewBag.DepartmentList = _dbContext.Departments.ToList();
            return View();
        }

        // Add the created employee above from Create - [HttpGet] to the Employees table
        [HttpPost]
        public IActionResult Create(Employee employee)
        {
            if (employee != null)
            {
                // Setting default Hiring Date to today's date
                employee.HiringDate = DateTime.Now;

                _dbContext.Employees.Add(employee);
                _dbContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View();
            }
        }

        // Call the Edit Employee View
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.DepartmentList = _dbContext.Departments.ToList();
            var model = _dbContext.Employees.Where(emp => emp.Id == id).FirstOrDefault();

            return View(model);
        }
        // Update edited employee information from Edit- HttpGet and save them in the DB.
        [HttpPost]
        public IActionResult Edit(int id, Employee employee)
        {
            var emp = _dbContext.Employees.Where(emp => emp.Id == id).FirstOrDefault();

            emp.EmployeeName = employee.EmployeeName;
            emp.DepartmentId = employee.DepartmentId;
            emp.EmployeeEmail = employee.EmployeeEmail;
            emp.BasicSalary = employee.BasicSalary;
            emp.HiringDate = employee.HiringDate;
            emp.BasicSalary = employee.BasicSalary;

            _dbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        // Remove selected employee from Employee table in the DB
        [HttpGet]
        public IActionResult Delete(int id, Employee employee)
        {
            var model = _dbContext.Employees.Where(emp => emp.Id == id).FirstOrDefault();
            if (model != null)
            {
                _dbContext.Employees.Remove(model);
                _dbContext.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

        #region Employee Reports
        [HttpGet]
        public IActionResult EmployeesReport()
        {
            var employees = _dbContext.Employees.ToList();
            var payrolls = _dbContext.Payrolls.ToList();

            // Creating new reports object
            var model = new EmployeeReportsViewModels
            {
                EmployeeCount = employees.Count(),
                TotalSSA = payrolls.Sum(pay => pay.SocialSecurityAmount),
                TotalBasicSalaries = employees.Sum(pay => pay.BasicSalary),
                TotalBonuses = payrolls.Sum(pay => pay.Bonus),
                TotalNetSalary = payrolls.Sum(pay => pay.NetSalary)
            };

            return View(model);
        }
        #endregion
    }
}

Backend/Core/Practice/HumanResourcesApp/HumanResourcesApp/Controllers/PayrollController.cs
// Ignore Spelling: App

using HumanResourcesApp.Data;
using HumanResourcesApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;  // for using ViewBag
using Microsoft.EntityFrameworkCore;

namespace HumanResourcesApp.Controllers
{
    public class PayrollController : Controller
    {
        #region Fields
        private AppDbContext _dbContext;
        #endregion

        #region Constructors 
        public PayrollController(AppDbContext appDbContext)
        {
            this._dbContext = appDbContext;
        }
        #endregion

        #region Action Methods

        #endregion
        public IActionResult Index()
        {
            var payroll = _dbContext.Payrolls
                .Include(pay => pay.Employee);

            return View(payroll);
        }

        [HttpGet]
        public IActionResult Create()
        {
            // Employees List drop-menu in Create View
            ViewBag.EmployeesList = new SelectList
                (
               _dbContext.Employees.ToList(),
               "Id",
               "EmployeeName"
               );
            return View();
        }
        [HttpPost]
        public IActionResult Create(Payroll payroll)
        {

            payroll.NetSalary = CalcNetSalary(payroll: payroll);
            payroll.CreatedBy = "Admin";
            payroll.TS = DateTime.Now;

            _dbContext.Payrolls.Add(payroll);
            _dbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        // Calculate NetSalary method
        public decimal CalcNetSalary(Payroll payroll)
        {
            var employee = _dbContext.Employees
                .FirstOrDefault(emp => emp.Id == payroll.EmployeeID);

            decimal netSalary = 0;

            if (employee != null)
            {
                decimal basicSalary = employee.BasicSalary; // Get Basic salary from DB
                payroll.BasicSalary = basicSalary;                // and put it in the Payroll field

                decimal bonus = payroll.Bonus;
                decimal ssa = payroll.SocialSecurityAmount;
                decimal leavesAmount = (basicSalary / 30 / 8) *
                    Convert.ToDecimal(payroll.Leaves);

                netSalary = basicSalary + bonus - ssa - leavesAmount;
            }

            return netSalary;
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.EmployeesList = new SelectList
                (
                    _dbContext.Employees.ToList(),
                    "Id", "EmployeeName"
                );

            var model = _dbContext.Payrolls.Where(pay => pay.Id == id).FirstOrDefault();

            return View("Create", model);
        }
        [HttpPost]
        public IActionResult Edit(int id, Payroll payroll)
        {
            var model = _dbContext.Payrolls.Where(payroll => payroll.Id == id).FirstOrDefault();

            model.EmployeeID = payroll.EmployeeID;
            model.PayrollDate = payroll.PayrollDate;
            model.Bonus = payroll.Bonus;
            model.SocialSecurityAmount = payroll.SocialSecurityAmount;
            model.Leaves = payroll.Leaves;
            model.NetSalary = payroll.NetSalary;
            model.Employee = payroll.Employee;

            _dbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Delete(int id, Payroll payroll)
        {
            var model = _dbContext.Payrolls.Where(emp => emp.Id == id).FirstOrDefault();
            if (model != null)
            {
                _dbContext.Payrolls.Remove(model);
                _dbContext.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult<decimal> GetBasicSalary(int employeeId)
        {
            var basicSalary = _dbContext.Employees.FirstOrDefault(emp => emp.Id == employeeId).BasicSalary;

            return basicSalary;
        }

    }
}

Backend/Core/Practice/HumanResourcesApp/HumanResourcesApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HumanResourcesApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HumanResourcesApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HumanResourcesApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Payroll" asp-action="Index">Payroll</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="EmployeesReport">Reports</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area="Accounting"
                               asp-controller="AccPayroll"
                               asp-action="Index">
                                Accounting Payroll
                            </a>
                        </li>

                        <il class="nav-item">
                            <a class="nav-link text-dark"
                               asp-controller="Account"
                               asp-action="Register">
                                Register
                            </a>
                        </il>
                        <il class="nav-item">
                            <a class="nav-link text-dark"
                               asp-controller="Account"
                               asp-action="Login">
                                Login
                            </a>
                        </il>
                    </ul>

                    @if (_signInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <il class="nav-item">
                            Welcome @User.Identity?.Name
                                <a class="nav-link text-dark"
                                   asp-controller="Account"
                                   asp-action="Logout">
                                    Logout
                                </a>
                            </il>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <il class="nav-item">
                                <a class="nav-link text-dark"
                                   asp-controller="Account"
                                   asp-action="Login">
                                    Log In
                                </a>
                            </il>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HumanResourcesApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>